install.packages("arules")
install.packages("arulesViz")
library(arules)
library(arulesViz)
data(Groceries)
View(Groceries)
str(Groceries)
freq<-head(Groceries@itemInfo, n=12)
head(Groceries)
inspect(freq)
str(freq)
View(freq)
itemFrequencyPlot(Groceries, topN=20, type="absolute")
